schema_version = "1.0.0"

id = "optiploy"
version = "1.7.1"
name = "OptiPloy: Rig Spawner"
tagline = "Improve your workflow with smarter linking tools"
maintainer = "hisanimations <hisprofile029@gmail.com"
type = "add-on"
tags = ["Pipeline", "Animation", "Rigging", "Import-Export"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
[permissions]
files = "Read and save .blend and folder entries"